dist: trusty
sudo: false

language: node_js
node_js:
  - '6'

addons:
  apt:
    packages:
      - google-chrome-stable

before_install:
  - npm install -g karma
  - npm install -g node-gyp

install:
  - npm install

before_script:
  - ng build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - ng test --single-run
  - ng e2e
